name: Auto-merge when ready

on:
  pull_request_target:
    types: [opened, synchronize, reopened]
  check_suite:
    types: [completed]

jobs:
  automerge:
    if: ${{ !github.event.pull_request || github.event.pull_request.draft == false }}
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      statuses: read

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Merge PR if possible
        run: node .github/scripts/auto-merge.js
        env:
          token: ${{ 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 }}

