name: Security Audit

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
    npm-audit:
      runs-on: self-hosted
      steps:
        - uses: actions/setup-node@v4
          with:
            node-version: '20'
        - uses: actions/checkout@v4
        - run: npm ci
        - run: npm audit --production --audit-level=high

